import Head from "next/head";

const Header = ({title}) => {
  title= title.charAt(0).toUpperCase() + title.slice(1)
    return ( 
        <Head>
        <title className="capitalize">{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
     );
}
 
export default Header;