import Head from 'next/head'
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className='grid-container grid-container--home '>
  <div>
  <h1 className='text-accent fs-500 ff-sans-cond letter-spacing-1 uppercase '>So, you want to travel to
  <span className="fs-900 ff-serif text-light dblock">Space</span></h1>
  <p>
  Let’s face it; if you want to go to space, you might as well genuinely go to 
  outer space and not hover kind of on the edge of it. Well sit back, and relax 
  because we’ll give you a truly out of this world experience! 
  </p>
  </div>
  <div>
  <Link href="/destination"><button data-type='explore-btn'>Explore</button></Link>
  </div>
  </div>
    </>
  )
}
